"""
Common data types, interface contracts, configuration schemas, and mocks.
"""

from src.common.types import (
    CoordinateSystem,
    FoveationLevelConfig,
    GridCell,
    PointCloudFrame,
    SemanticClass,
    SemanticPointCloud,
    SemanticMap,
    TraversabilityScore,
    TelemetryMetrics,
)
from src.common.interfaces import (
    IBenchmarkEngine,
    IDatasetAdapter,
    IFoveatedGrid,
    IPipelineIntegrator,
    IPreprocessor,
    ISemantic25DMapper,
    ISemanticPerception,
    ISyntheticSceneGenerator,
    ITemporalMapUpdater,
    ITraversabilityAnalyzer,
    IVisualizer,
)
from src.common.config import SystemConfig, load_config
from src.common.mocks import (
    MockBenchmarkEngine,
    MockDatasetAdapter,
    MockFoveatedGrid,
    MockPipelineIntegrator,
    MockPreprocessor,
    MockSemantic25DMapper,
    MockSemanticPerception,
    MockSyntheticSceneGenerator,
    MockTemporalMapUpdater,
    MockTraversabilityAnalyzer,
    MockVisualizer,
)

__all__ = [
    "CoordinateSystem",
    "FoveationLevelConfig",
    "GridCell",
    "PointCloudFrame",
    "SemanticClass",
    "SemanticPointCloud",
    "SemanticMap",
    "TraversabilityScore",
    "TelemetryMetrics",
    "IBenchmarkEngine",
    "IDatasetAdapter",
    "IFoveatedGrid",
    "IPipelineIntegrator",
    "IPreprocessor",
    "ISemantic25DMapper",
    "ISemanticPerception",
    "ISyntheticSceneGenerator",
    "ITemporalMapUpdater",
    "ITraversabilityAnalyzer",
    "IVisualizer",
    "SystemConfig",
    "load_config",
    "MockBenchmarkEngine",
    "MockDatasetAdapter",
    "MockFoveatedGrid",
    "MockPipelineIntegrator",
    "MockPreprocessor",
    "MockSemantic25DMapper",
    "MockSemanticPerception",
    "MockSyntheticSceneGenerator",
    "MockTemporalMapUpdater",
    "MockTraversabilityAnalyzer",
    "MockVisualizer",
]
